first commit
JoonasHeinonen/escape-from-zordoom-prison pull request #65
Opened 2024-06-05 03:39 UTC by NathanCenter

## [Ticket name / description](https://trello.com/b/vThoQnyu/escape-from-zordoom-prison)

<Paste the media recorded of your feature in the action, e.g. a video or an image>

## Changes:
 - Change 1.
 - Change 2.
 - etc...

## How to test:
 - Test step 1.
 - Test step 2
 - etc...

## Sources cited:
 - [Source 1](https://www.example.com/)

2024-07-20 11:02 UTC, JoonasHeinonen requested changes
Minor changes required.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/world/ladder.gd
> +
Remove this emptyline

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/world/ladder.gd
> +
Remove these empty lines.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/world/ladder.gd
> +			print("enter ladder")
Remove print.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/world/ladder.gd
> +			print("exit ladder")
Remove print.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/Player/player.gd
> +	if Input.is_action_just_released("ui_climb_up") and at_ladder == true:
Add a space above this line.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/Player/player.gd
> +		if Globle.player_character == "Rivet":
Add a space above this line.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/Player/player.gd
> +	if Input.is_action_just_released("ui_climb_down") and at_ladder == true:
Add a space above this line.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/Player/player.gd
> +	if at_ladder == false:
Add a space above this line.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/Player/player.gd
>  	if Input.is_action_pressed("ui_ranged_sniper_aim") && !Input.is_action_pressed("ui_melee_attack"):
Add a space above this line.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/Player/player.gd
> +		print(player_velocity.y)
Remove print.

2024-07-20 11:02 UTC, JoonasHeinonen commented on src/scripts/Player/player.gd
> +
Remove these empty spaces, keep the line empty.

2024-07-26 20:08 UTC, JoonasHeinonen approved these changes
LGTM.

2024-08-03 15:56 UTC, JoonasHeinonen requested changes
I will finish this...

2024-08-03 16:22 UTC, NathanCenter commented
> I will finish this...

um... what seems to be the issue is it the animation or the code?

2024-08-10 00:44 UTC, NathanCenter commented
Looks good to me.

2024-08-11 15:28 UTC, JoonasHeinonen approved these changes
LGTM.

2024-08-11 15:42 UTC, merged