Feature/more levels
JoonasHeinonen/escape-from-zordoom-prison pull request #67
Opened 2024-12-07 22:06 UTC by JoonasHeinonen

## [Make more levels](https://trello.com/c/jlo8k1aR/88-make-more-levels)

## Changes:
 - Added mission parameters.
 - More tiles.
 - Sprite sheets enhanced.
 - Added sprite sheets for Nefarious, F44, mission parameter card.
 - Optimized code.

2024-12-09 00:05 UTC, NathanCenter commented on src/scripts/npc/npc.gd
> +	if (Globle.player_character == "Rivet" and get_node_or_null('DialogNode') == null and Input.is_action_just_pressed("ui_accept") and active):
when trying to go to angela as rivet it is not activating for some reason.
![image](https://github.com/user-attachments/assets/728e603a-ef4d-4823-84ff-ce03110037e7)

2024-12-14 23:37 UTC, NathanCenter commented on src/scripts/world/levels/level_data.gd
>  	set_music(default_music, default_music_stream)
There is no music... did we add music to the level?

2024-12-14 23:49 UTC, NathanCenter commented
https://github.com/user-attachments/assets/017ea03d-29bf-4051-9a8e-a8d0c9eae156
Odd glitch where one side of sliding is not working for the staircase.

2024-12-15 00:15 UTC, NathanCenter commented
![image](https://github.com/user-attachments/assets/1a0fa35f-00e1-45ef-9cfa-b9f22172bbfa)
Why is the sprite so dark in the area level?

2024-12-15 00:16 UTC, NathanCenter commented
![image](https://github.com/user-attachments/assets/8a66e163-4d47-4434-8d52-89dbd7d20bd9)
Are you going to move this to the boss and when he dies it drops this key card?

2024-12-19 00:13 UTC, NathanCenter requested changes

2024-12-20 11:31 UTC, JoonasHeinonen commented on src/scripts/npc/npc.gd
> +					"F44":
Later.

2024-12-20 12:39 UTC, JoonasHeinonen commented on src/scripts/npc/npc.gd
>  		player = get_parent().get_parent().get_parent().get_parent().get_node('player')
You're right. I discovered a better way to find the player node: `player = get_tree().get_root().get_node("Level/player")`

2024-12-20 13:21 UTC, JoonasHeinonen commented on scenes/Levels/test_level.tscn
> +"retrieveKeyCard": false
Yes, it was in the menu, but not visible, yet.

2024-12-29 20:07 UTC, NathanCenter commented
Everything looks good to me!

2024-12-29 20:08 UTC, NathanCenter approved these changes

2024-12-30 13:53 UTC, merged